### ISSUE TITLE
CSS Craft  💅

### ISSUE THREAD

**Issue by lihroff** [Tommy-White/Archive#16]
***
## 1. 使用`<img src srcset ...` 实现响应式图像
> 定义不同大小的同一图像，允许浏览器来选择合适的图像源。

```jsx
// xxx/logo.png & xxx/logo@2x.png
<Img
  src={`${ICON_BASE}/logo.png`}
  srcset={`${ICON_BASE}/logo@2x.png 2x`}
  ...
/>

/*** basic usage 
  srcset=" 
      url size,
      url size
  "
***/

```
Read more: https://html.com/attributes/img-srcset

***

## 2. 图片悬浮缩放
> 悬停缩放（zoom-on-hover）效果是一种吸引注意力到可点击图像的好方法。当用户将鼠标悬停在其上方时，图像会略微放大，但其尺寸保持不变。

1. 在 img 中设置动画过渡时间，并在 `:hover` 选择器上设置图片放大效果;
2. 使用 div 等元素包裹 img 并设置 `overflow` 属性为 hidden, 并固定其`width, height` 属性.

```css
.inner-img {
  transition: 0.3s;
}
.inner-img:hover {
  transform: scale(1.1);
}

.img-wrapper {  
  width: 400px;
  height: 400px;
  overflow: hidden; 
}
```

Demo: https://codepen.io/woo_tommy_l/pen/oNNpGXN

***

## 3. 类微信扫一扫渐变条码
> 通过 [`radial-gradient()`](https://developer.mozilla.org/en-us/docs/Web/CSS/radial-gradient) 函数，其由一个从原点辐射开的在两个或者多个颜色之前的渐变组成。

```css
#example {
  background: radial-gradient(150px 15px ellipse at bottom, green 0%, transparent 100%)
  // background: radial-gradient(150px 15px ellipse at 50% 100%, green 0%, transparent 100%)
}
```

Demo: https://www.w3schools.com/code/tryit.asp?filename=GCVMITBN6HOR

***

## 4.多行文本省略...
> 使用 CSS [`line-clamp`](https://caniuse.com/?search=line-clamp) 属性设置截断文本的最大行数.

Demo : https://codepen.io/woo_tommy_l/pen/NWRevmK

注⚠️：
  - line-clamp 需要多个属性的组合才可以实现效果，并且处于提议阶段需要`-webkit-`前缀。
  - 可以使用 [`clamp.js`(https://github.com/josephschmitt/Clamp.js)]来动态设置
