### ISSUE TITLE
[译] A Complete Guide to Flexbox [WIP]

### ISSUE THREAD

**Issue by lihroff** [Tommy-White/Archive#17]
在写一些应用时常常直接使用原始的css flex，其中属性较多经常需要参考[CSS_TRICKS](https://css-tricks.com/snippets/css/a-guide-to-flexbox/)上的文章，想想干脆直接将该文章 trans 为中文方便查看。

# Flexbox完整指南
> 我们的CSS flexbox布局综合指南。该完整指南解释有关flexbox的一切，专注父元素（flex容器 |` flex container `）和子元素（flex元素 |` flex items `）的所有不同可能属性。它还包括历史，演示，模式和浏览器支持图表(可能未完全搬运)。
> 翻译中`弹性item` 可指flex 容器中的item，亦可指期长宽可伸缩变化。

## 背景
Flexbox布局（flex box）模块（截至2017年10月的[W3C候选推荐标准](https://www.w3.org/TR/css-flexbox/)）旨在提供更有效的布局方式，容器中的项目之间对齐和分配空间，即使它们的大小未知和/或动态（因此单词“flex”）。

flex布局背后主要的想法是赋予修改容器子元素宽/高（和顺序）以最好的方式填充可用空间。（主要适用于所有类型的显示设备和屏幕尺寸）。Flex容器拉伸项目以填充可用空间，或缩小它们以防止溢出。

最重要的是，flexbox布局与方向无关，而不是常规布局（基于垂直的块和基于水平的内联块）。虽然这些页面适用于页面，但它们缺乏灵活性（没有双关语）来支持大型或复杂的应用程序（特别是在方向更改，调整大小，拉伸，缩小等方面）。

**注意**：Flexbox布局最适合应用程序的组件和小规模布局，而Grid布局则适用于更大规模的布局。

## 基础 & 术语
flexbox是一整套系统而不是一个单一属性，它包含了一系列的属性。其中一些是被用在容器上的（父元素，被叫做“flex container”）其他的则被用来设置子元素（被叫做“flex items”）。

如果“常规”布局基于块和内联流方向，则flex布局基于“flex-flow directions”。请查看规范中的这个图，解释flex布局背后的主要思想。

![image](https://user-images.githubusercontent.com/24240963/59486777-14be1a00-8ead-11e9-8732-28e84d35a326.png)
_注： 图中红绿蓝字是**术语**而不是真实css属性_

子元素将被以此放置在`main axis`(从`main-start`至`main end`)或者`corss-axis`(从`corss-start`至`corss end`) [注：主轴或纵轴]

**主轴 main axis**：主轴数flex 容器沿主要方向放置item的轴。 ⚠️，它不一定就是水平方向，还取决与`flex-direction`属性

**main-start | main-end**： flex item被放置在flex container中起始与main-start终止与main-end

**main-size**：从main-start到main-end的长度它决定了flex container的width或者height

**cross-axis**：垂直于主轴的轴称为横轴。其方向取决于主轴方向。

[其余cross-* 类比与 main-*] ......

***
![image](https://user-images.githubusercontent.com/24240963/59488599-9f554800-8eb2-11e9-8216-363ce6005562.png)

_以下介绍真实设置在父元素的 css 属性_

### display
在元素上声明display属性则定义了一个flex container；内联或块级取决于给定的值。它为所有直接孩子提供了flex上下文。

```css
.container {
  display: flex; /* or inline-flex */
}
// Note that CSS columns have no effect on a flex container.
```

### flex-direction

![image](https://user-images.githubusercontent.com/24240963/59487784-3d93de80-8eb0-11e9-8d6b-6f9759c6dd1c.png)

次属性定义了主轴（main-axis），导致flex item在flex contain中的排列顺序。

```css
.container {
  flex-direction: row(default) | row-reverse | column | column-reverse;
}
```

- row: (默认)： 在`left to right`从左至右；在`right to left`从右至左
- row-reverse: 与row相反
- column： 与`row`类似，但是是从上至下
- column-reverse： 与`column`相反

### flex-wrap
![image](https://user-images.githubusercontent.com/24240963/59487799-4b496400-8eb0-11e9-8916-03f2e4d8520e.png)

默认，flex items将试图排列在一行。您可以更改它并允许item根据需要使用此属性进行换行。

```css
.container{
  flex-wrap: nowrap(default) | wrap | wrap-reverse;
}
```

- nowrap: (默认)所有flex items将在一行
- wrap： 放不下的item 将换行（从上至下）
- wrap-reverse： 与`wrap`相反

### flex-flow

缩写

```css
flex-flow: <‘flex-direction’> || <‘flex-wrap’>
```

### justify-content：
![image](https://user-images.githubusercontent.com/24240963/59488035-ffe38580-8eb0-11e9-82b4-789a47bdaab1.png)

此定义沿主轴的对其方式。它有助于构建item之间的额外空间（`当item都没有flex-grow时`）或者是弹性的但已经达到最大值。It also exerts some control over the alignment of items when they overflow the line.

```css
.container {
  justify-content: flex-start(default) | flex-end | center | space-between | space-around | space-evenly;
}
```

### align-items
![image](https://user-images.githubusercontent.com/24240963/59488200-7e402780-8eb1-11e9-84b9-910a4e0ffdc5.png)

此定义了如何沿当前行的纵轴布置弹性item的默认行为。可以将其视为纵轴（垂直于主轴）的对齐版本。

```css
.container {
  align-items: stretch(default) | flex-start | flex-end | center | baseline;
}
```

### align-content

![image](https://user-images.githubusercontent.com/24240963/59488376-fa3a6f80-8eb1-11e9-8689-094e2bc06ae4.png)

This aligns a flex container's lines within when there is extra space in the cross-axis, similar to how justify-content aligns individual items within the main-axis.

当纵轴上有额外的空间时，这会将flex容器的线对齐，类似于在主轴内对齐内容的内容。

**注意：**此属性对应只有一行flex item没有效果
.container {
  align-content: flex-start | flex-end | center | space-between | space-around | stretch(default)(仍然受限与max-height/max-width);
}

***
![image](https://user-images.githubusercontent.com/24240963/59488644-b431db80-8eb2-11e9-97fa-336cfbcd889b.png)

_以下介绍真实设置在子元素的 css 属性_

### order
![image](https://user-images.githubusercontent.com/24240963/59488758-f6f3b380-8eb2-11e9-8704-a9e89b31829f.png)

默认情况下，flex item按源顺序排列。但是，order属性控制它们在flex容器中的显示顺序。

```css
.item {
  order: <integer>; /* 默认 0 */
}
```

### flex-grow

![image](https://user-images.githubusercontent.com/24240963/59488859-420dc680-8eb3-11e9-93f3-f417bf192d86.png)

这定义了flex item在必要时拉伸的能力。这根据每一个item的比例来分配
> 默认值0代表不会被拉伸, 其他值按照分配比例划分

```css
.item {
  flex-grow: <number>; /* 默认 0 */
  // 负数是非法的
}
```

### flex-shrink
这定义了flex item在必要时缩小的能力。
> 默认为1代表总items超过了 flex container 的大小会被均匀的收缩(但父元素中flex-wrap必须是 nowrap)

```css
.item {
  flex-shrink: <number>; /* 默认 1 */
  // 负数是非法的
}
```

### flex-basis
This defines the default size of an element before the remaining space is distributed. It can be a length (e.g. 20%, 5rem, etc.) or a keyword. The auto keyword means "look at my width or height property" (which was temporarily done by the main-size keyword until deprecated). The content keyword means "size it based on the item's content" - this keyword isn't well supported yet, so it's hard to test and harder to know what its brethren max-content, min-content, and fit-content do.

```css
.item {
  flex-basis: <length> | auto; /* default auto */
}
```
If set to 0, the extra space around content isn't factored in. If set to auto, the extra space is distributed based on its flex-grow value. [See this graphic](https://www.w3.org/TR/css-flexbox-1/images/rel-vs-abs-flex.svg).

### flex
This is the shorthand for flex-grow, flex-shrink and flex-basis combined. The second and third parameters (flex-shrink and flex-basis) are optional. Default is 0 1 auto.

```css
.item {
  flex: none | [ <'flex-grow'> <'flex-shrink'>? || <'flex-basis'> ]
}
```

**It is recommended that you use this shorthand property rather than set the individual properties.** The short hand sets the other values intelligently.

### align-self
![image](https://user-images.githubusercontent.com/24240963/59489645-55219600-8eb5-11e9-8eb2-57c8390359cf.png)

此允许改写某一个item默认但对其方式。
请参阅align-items说明以了解可用值。

```css
.item {
  align-self: auto | flex-start | flex-end | center | baseline | stretch;
}
```
请注意，float，clear和vertical-align对flex item没有影响。

## 浏览器支持
由版本分解"flexbox"：
-（new）表示规范中的最新语法（例如display：flex;）
- （tweener）表示2011年的一种奇怪的非官方语法（例如display：flexbox;）
- （old）表示2009年的旧语法（例如display：box;）

![image](https://user-images.githubusercontent.com/24240963/59895036-851cec00-9415-11e9-86eb-6c386cc6e336.png)
(大致兼容性范围)
